-- ## 4 Part 2: Altering Tables
--
-- Create a library_schema_changes.sql file containing DDL SQL statements to perform the following modifications:
--
-- 1. Add a new column email (TEXT, Not Null) to the Members table.
-- 2. Add a new constraint to the Books table ensuring that the price is at least 5.
--     - Note: You may need to DROP something to do the task 2
--
-- ### 4.1 Submission Instructions
--
-- - Save your SQL commands in the two .sql files and put it in a folder named l04_firstname Compress the folder in .zip format.
--     - Example: lab4_john.zip
-- - Submit the file to the Learning Hub.
